services:
  web:
    build: .
    command: python3 -u app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/todo
    links:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"